source 'https://rubygems.org'

gem 'airborne'
gem 'capistrano'
gem 'capybara'
gem 'poltergeist'
gem 'rspec'
gem 'capybara_error_intel'
gem 'rubocop', require: false
gem 'rubocop-rspec'
gem 'capybara-screenshot'
gem 'logging'
gem 'byebug'
gem 'capistrano-bundler'
gem 'selenium-webdriver'
gem 'capybara-webkit'
