version: "3"
services:
  selenium_hub:
    image: selenium/hub
    ports:
      - 4444:4444
    expose:
      - 4444
  firefox_node:
    image: selenium/node-firefox-debug
    ports:
      - 4577:5900
    expose:
      - 4577
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
  chrome_node:
    image: selenium/node-chrome-debug
    ports:
      - 4578:5900
    expose:
      - 4578
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
